### PR TITLE
fix: bonsai needs libldap2-dev apt recommends

### PR DESCRIPTION
**Pull request by yee379**
bonsai/ldap queries fail due to missing libraries with the following error:

```
bonsai.errors.ConnectionError: Can't contact LDAP server. (unknown error code) (0xFFFF [-1])
```

this patch fixes this by disabling the `--no-install-recommends` for `libldap2-dev`.

### CODE REVIEW

**Comment by rra** [comment]
I don't understand -- libldap2-dev doesn't recommend anything. What specific packages does this cause to be installed that weren't installed before?

**Comment by yee379** [comment]
```
# apt-get install -y --no-install-recommends libldap2-dev
 ---> Running in 39af7a35715a
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libldap-2.4-2 libsasl2-2 libsasl2-modules-db
Recommended packages:
  libldap-common libsasl2-modules
The following NEW packages will be installed:
  libldap-2.4-2 libldap2-dev libsasl2-2 libsasl2-modules-db
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
```

```
# apt-get install -y libldap2-dev
 ---> Running in e637365b095c
Reading package lists...
Building dependency tree...
Reading state information...
The following additional packages will be installed:
  libldap-2.4-2 libldap-common libsasl2-2 libsasl2-modules libsasl2-modules-db
Suggested packages:
  libsasl2-modules-gssapi-mit | libsasl2-modules-gssapi-heimdal
  libsasl2-modules-ldap libsasl2-modules-otp libsasl2-modules-sql
The following NEW packages will be installed:
  libldap-2.4-2 libldap-common libldap2-dev libsasl2-2 libsasl2-modules
  libsasl2-modules-db
0 upgraded, 6 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by rra** [comment]
Oh, maybe libldap-common, which is recommended by the library? Let's install that explicitly rather than enabling recommends.

**Comment by rra** [comment]
Ah, yes, and also libsasl2-modules. We should install those explicitly.

**Comment by rra** [comment]
Merged in #409 to simplify the Git commit structure. Thanks!

**Pull request closed without merging**
