### PR TITLE
Tickets/DM-38058

### PR DESCRIPTION
**Pull request by gabrimaine**

### CODE REVIEW

**Comment by rra** [comment]
Sorry for the delay on this -- it got stuck behind some other work. I'm working on getting it merged now for the upcoming 9.1.0 release.

**Comment by rra** [comment]
I've refactored this a bit and added tests and documentation. Doing some research, it looks like OpenIDM was a failed open-core attempt, and now the only version of this software that exists and is maintained is ForgeRock Identity Management (that's what all their documentation calls it). "idm" is a very generic term (everything Gafaelfawr queries is an identity management system), so I renamed the configuration setting to `forgerock` and changed the fields to match our normal convention.

If you want to test in advance, there's a new Docker image available as the `tickets-DM-38058` tag. I'm going to work on the Phalanx integration shortly.

**Comment by rra** [comment]
BTW, refactoring work is in #712.

**Comment by gabrimaine** [comment]
Thanks @rra I will give a try asap. CC-IN2P3 is also moving from openIDM to Apache Syncope, so probably in the next months I will be forced to add a new component in gafaelfawr.

**Comment by gabrimaine** [comment]
I asked many time for this, hopefully one day...

**Comment by rra** [comment]
Equivalent code has now been merged in #712 and is in the 9.1.0 release. I also updated Phalanx with this configuration for your environment, although did not include the other nublado change in the code merged into Phalanx. If you rebase your Phalanx branch, you should hopefully get a working deployment with this support. If you run into any problems, let me know, and I can do a quick bug fix release.

**Pull request closed without merging**
